### PR TITLE
Avoid assigning objects to window

### PR DESCRIPTION
**Pull request by upsuper**
This bypasses some new stupid extensions.

### CODE REVIEW

**Comment by upsuper** [comment]
Stupid ones:
https://chrome.google.com/webstore/detail/cyberghost-webrtc-leak-pr/fcacplgecnjoapkgbbfdijidojncpijc
https://chrome.google.com/webstore/detail/webrtc-stopper/mfehokchlmjlkmlgjhkmlpcldcbcooec

**Comment by diafygi** [comment]
Thanks!

**Comment by ZimTester** [comment]
Nice fix, logical

**Comment by diafygi** [comment]
FYI, I bypassed [CyberGhost WebRTC-Leak protection](https://chrome.google.com/webstore/detail/cyberghost-webrtc-leak-pr/fcacplgecnjoapkgbbfdijidojncpijc) in commit 97685cbdca508043f8fabd286c8bb4ac421af85e, which added an eventlistener for dom injections to detect the iframe injection.

**Pull request merged**
