### PR TITLE
Invalidate any content script

### PR DESCRIPTION
**Pull request by upsuper**

### CODE REVIEW

**Comment by ZimTester** [comment]
As I've already [noticed](https://github.com/diafygi/webrtc-ips/pull/8#issuecomment-75899740), this fix doesn't bypass `"match_about_blank": true` in *manifest.json*

**Comment by upsuper** [comment]
No, it still bypassed. The only difference is that, the new version of Chrome extends the range of sandbox, and not allowing scripts also disallows webrtc objects fetched from the iframe to be used.

**Comment by ZimTester** [comment]
@upsuper So what to do to bypass it on new version of Chrome? For me it's still blocking (clear installation with empty profile).

**Comment by upsuper** [comment]
Yes, it fails to bypass the block now.

**Comment by upsuper** [comment]
But interestingly, I still can, though a bit more compilcated.

Will submit a new patch soon.

**Comment by ZimTester** [comment]
@upsuper Thx, will wait for it.

**Pull request merged**
