### PR TITLE
Bypass naive WebRTC blocking

### PR DESCRIPTION
**Pull request by upsuper**
This can bypass the Chrome extension "WebRTC Block".

### CODE REVIEW

**Comment by upsuper** [comment]
Ping?

**Comment by diafygi** [comment]
Sorry for the delay, I wanted to reach out to the WebRTC Block developers and give them a few days to update their extension. However, I have not heard back, so I will merge this pull request. Thanks!

**Comment by upsuper** [comment]
Actually, I don't think it is possible to fix this problem in a Chrome extension.

**Comment by emanueLczirai** [comment]
It appears to me that rebuilding chromium with `-Denable_webrtc=0` is the real way to disable WebRTC. (haven't tested yet)

**Comment by fippo** [comment]
@upsuper should be possible by adding
```
      "all_frames": true,
      "match_about_blank": true,
```
to the content_scripts section in the extension manifest. That way, the content script is executed on about:blank iframes as well.

**Comment by upsuper** [comment]
@fippo I don't think so. I don't think the browser should run any other script when one piece of script is running.

**Comment by fippo** [comment]
@upsuper take the webrtcblock source from chromes extension directory, modify the manifest.json as indicated, import it as your own extension. breaks the (awesome) iframe hack for me.

**Comment by upsuper** [comment]
@fippo then I just need to specify `iframe.sandbox = 'allow-same-origin'` in addition, the content script will be bypassed again :)

**Comment by upsuper** [comment]
@diafygi you probably could also add the code I just mentioned above to the detection script.

**Comment by diafygi** [comment]
Pull request please? Please update both the `README.md` and the `index.html`.

**Comment by upsuper** [comment]
OK, I'll do it later. It seems I can't change two files in one commit on Github directly.

**Comment by ZimTester** [comment]
@upsuper Nope, `iframe.sandbox = 'allow-same-origin'` doesn't bypass this @fippo's way
```javascript
   "content_scripts": [ {
      "all_frames": true,
      "match_about_blank": true,
```
is really break this **[webrtc-ips](https://diafygi.github.io/webrtc-ips/)**, tested on latest Chromium LKGR build for Win: **[#9662](https://build.chromium.org/p/chromium.lkgr/builders/Win/builds/9662)**
(chrome version: **43.0.2314.0**)

P.S. Also you can modify
```javascript
      "matches": [ "http://*/*", "https://*/*" ],
```
to
```javascript
      "matches": [ "http://*/*", "https://*/*", "file://*/*" ],
```
for a quick local check / for blocking from local host(s) files too.

**Comment by upsuper** [comment]
No, it still bypassed. The only difference is that, the new version of Chrome extends the range of sandbox, and not allowing scripts also disallows webrtc objects fetched from the iframe to be used.

**Comment by Piseth6655** [comment]
cf559b59

**Pull request merged**
